{
  "back": "Tilbage",
  "cancel": "Annuller",
  "close": "Luk",
  "managed_error_content": "Der opstod en uventet fejl. Vi har allerede logget denne fejl. Pr√∏v venligst igen senere.",
  "managed_error_oops": "Ups, noget gik galt",
  "no": "Nej",
  "ok": "OK",
  "submit": "Indsend",
  "system_language": "Systemsprog",
  "yes": "Ja"
}
